######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 15 21:20:21 2019
######################################################################

TEMPLATE = app
TARGET = threadtest
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ThreadTest.h
SOURCES += main.cpp ThreadTest.cpp
QT += widgets
